export interface ConfigureRestaurantModel {
  ambientPoints: number,
  smokingPoints: number,
  alcoholPoints: number,
  dateTimePoints: number,
  distancePoints: number,
  priceRangePoints: number,
  musicPoints: number,
  cuisinePoints: number,
  gardenPoints: number,
  parkingPoints: number,
  tvPoints: number,
  wifiPoints: number,
  baseAmbientPoints: number,
  baseSmokingPoints: number,
  baseAlcoholPoints: number,
  baseDateTimePoints: number,
  baseDistancePoints: number,
  basePriceRangePoints: number,
  baseMusicPoints: number,
  baseCuisinePoints: number,
  baseGardenPoints: number,
  baseParkingPoints: number,
  baseTvPoints: number,
  baseWifiPoints: number
}
