package ules;

import com.ftn.uns.ac.rs.love_and_food.model.enums.Age;
import com.ftn.uns.ac.rs.love_and_food.model.User;

import com.ftn.uns.ac.rs.love_and_food.util.DateUtil;

//Age
rule "Partner Age_18_20"
	agenda-group "partner-age"
	when
		$u: User(18 <= DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth)<= 20) @Watch(!ageGroup)
	then
		System.out.println("Set partner age - Age_18_20");
		modify($u){setAgeGroup(Age.AGE_18_20);};
end;

rule "Partner Age_20_25"
	agenda-group "partner-age"
	when
		$u: User(20 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 25) @Watch(!ageGroup)
	then
		System.out.println("Set partner age - Age_20_25");
		modify($u){setAgeGroup(Age.AGE_20_25);};
end;

rule "Partner Age_25_30"
	agenda-group "partner-age"
	when
		$u: User(25 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 30) @Watch(!ageGroup)
	then
		System.out.println("Set partner age - AGE_25_30");
		modify($u){setAgeGroup(Age.AGE_25_30);};
end;

rule "Partner Age_30_40"
	agenda-group "partner-age"
	when
		$u: User(30 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 40) @Watch(!ageGroup)
	then
		System.out.println("Set partner age - Age_30_40");
		modify($u){setAgeGroup(Age.AGE_30_40);};
end;

rule "Partner Age_40_50"
	agenda-group "partner-age"
	when
		$u: User(40 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 50) @Watch(!ageGroup)
	then
		System.out.println("Set partner age - AGE_40_50");
		modify($u){setAgeGroup(Age.AGE_40_50);};
end;
	
rule "Partner Age_50_65"
	agenda-group "partner-age"
	when
		$u: User(50 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 65) @Watch(!ageGroup)
	then
		System.out.println("Set partner age - Age_50_65");
		modify($u){setAgeGroup(Age.AGE_50_65);};
end;

rule "Partner Age_65+"
	agenda-group "partner-age"
	when
		$u: User(65 < DateUtil.getDiffYears(dateOfBirth)) @Watch(!ageGroup)
	then
		System.out.println("Set partner age - Age_65+");
		modify($u){setAgeGroup(Age.AGE_65_PLUS);};
end;