package rules;
import com.ftn.uns.ac.rs.love_and_food.model.Match;
import java.util.List;
import java.time.LocalDate;
global List<Match> resultMatches;

rule "Get all matches made in range 0"
	agenda-group "match-interval"
	when
		accumulate(
			Match($m: this, $matchDate: matchDate, $matchDate.isAfter(LocalDate.parse("2020-01-01")),
				$matchDate.isBefore(LocalDate.parse("2020-12-31"))),
	        $matches: collectList($m)
	    )
	then
		resultMatches.addAll($matches);
		System.out.println("Found all matches for time interval from " + "2020-01-01" + " to " + "2020-12-31");
end


