package rules;

import com.ftn.uns.ac.rs.love_and_food.model.User;
import com.ftn.uns.ac.rs.love_and_food.model.PartnerRequirements;

import com.ftn.uns.ac.rs.love_and_food.model.enums.Children;
import com.ftn.uns.ac.rs.love_and_food.model.enums.SexualOrientation;
import com.ftn.uns.ac.rs.love_and_food.model.enums.Gender;
import com.ftn.uns.ac.rs.love_and_food.model.enums.DesiredRelationship;
import com.ftn.uns.ac.rs.love_and_food.model.enums.Age;

import com.ftn.uns.ac.rs.love_and_food.util.DateUtil;

//Children
rule "Partner Requirements set children"
	agenda-group "partner-requirements"
	when
		$u: User($children: children);
		$pr: PartnerRequirements(userId==$u.id, children == null);
	then
		System.out.println("Partner Requirements set children - " + $children);
		modify($pr){setChildren($children);};
end;

//Relationship
rule "Partner Requirements set desired relationship status"
	agenda-group "partner-requirements"
	when
		$u: User( $desiredRelationship: desiredRelationship);
		$pr: PartnerRequirements(userId==$u.id, desiredRelationship == null);
	then
		System.out.println("Partner Requirements set desired relationship status - " + $desiredRelationship);
		modify($pr){setDesiredRelationship($desiredRelationship);};
end;

//Age
rule "Age_18_20"
	agenda-group "partner-requirements"
	when
		$u: User(18 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth)<= 20);
		$pr: PartnerRequirements(userId==$u.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Partner Requirements set ideal age - Age_18_20");
		modify($pr){setIdealAge(Age.AGE_18_20),getSuitableAge().add(Age.AGE_20_25),getSuitableAge().add(Age.AGE_18_20);};
end;

rule "Age_20_25"
	agenda-group "partner-requirements"
	when
		$u: User(20 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 25);
		$pr: PartnerRequirements(userId==$u.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Partner Requirements set ideal age - Age_20_25");
		modify($pr){setIdealAge(Age.AGE_20_25),getSuitableAge().add(Age.AGE_18_20),getSuitableAge().add(Age.AGE_25_30),getSuitableAge().add(Age.AGE_20_25);};
end;

rule "Age_25_30"
	agenda-group "partner-requirements"
	when
		$u: User(25 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 30);
		$pr: PartnerRequirements(userId==$u.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Partner Requirements set ideal age - AGE_25_30");
		modify($pr){setIdealAge(Age.AGE_25_30),getSuitableAge().add(Age.AGE_20_25),getSuitableAge().add(Age.AGE_30_40),getSuitableAge().add(Age.AGE_25_30);};
end;

rule "Age_30_40"
	agenda-group "partner-requirements"
	when
		$u: User(30 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 40);
		$pr: PartnerRequirements(userId==$u.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Partner Requirements set ideal age - Age_30_40");
		modify($pr){setIdealAge(Age.AGE_30_40),getSuitableAge().add(Age.AGE_25_30),getSuitableAge().add(Age.AGE_40_50),getSuitableAge().add(Age.AGE_30_40);};
end;

rule "Age_40_50"
	agenda-group "partner-requirements"
	when
		$u: User(40 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 50);
		$pr: PartnerRequirements(userId==$u.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Partner Requirements set ideal age - AGE_40_50");
		modify($pr){setIdealAge(Age.AGE_40_50),getSuitableAge().add(Age.AGE_30_40),getSuitableAge().add(Age.AGE_50_65),getSuitableAge().add(Age.AGE_40_50);};
end;
	
rule "Age_50_65"
	agenda-group "partner-requirements"
	when
		$u: User(50 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 65);
		$pr: PartnerRequirements(userId==$u.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Partner Requirements set ideal age - Age_50_65");
		modify($pr){setIdealAge(Age.AGE_50_65),getSuitableAge().add(Age.AGE_40_50),getSuitableAge().add(Age.AGE_65_PLUS),getSuitableAge().add(Age.AGE_50_65);};
end;

rule "Age_65+"
	agenda-group "partner-requirements"
	when
		$u: User(65 < DateUtil.getDiffYears(dateOfBirth));
		$pr: PartnerRequirements(userId==$u.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Partner Requirements set ideal age - Age_65+");
		modify($pr){setIdealAge(Age.AGE_65_PLUS),getSuitableAge().add(Age.AGE_50_65),getSuitableAge().add(Age.AGE_65_PLUS);};
end;

//Preffered gender
rule "M + Straight"
	agenda-group "partner-requirements"
	when
		$u: User(gender==Gender.MALE, sexualOrientation==SexualOrientation.HETEROSEXUAL );
		$pr: PartnerRequirements(userId==$u.id, prefferedGender == null);
	then
		System.out.println("Partner Requirements for M + Straight set preffered gender - FEMALE");
		modify($pr){setPrefferedGender(Gender.FEMALE);};
end;

rule "M + Homosexual"
	agenda-group "partner-requirements"
	when
		$u: User(gender==Gender.MALE, sexualOrientation==SexualOrientation.HOMOSEXUAL );
		$pr: PartnerRequirements(userId==$u.id, prefferedGender == null);
	then
		System.out.println("Partner Requirements for M + Homosexual set preffered gender - MALE");
		modify($pr){setPrefferedGender(Gender.MALE);};
end;

rule "Bisexual"
	agenda-group "partner-requirements"
	when
		$u: User(gender==Gender.MALE, sexualOrientation==SexualOrientation.BISEXUAL );
		$pr: PartnerRequirements(userId==$u.id, prefferedGender == null);
	then
		System.out.println("Partner Requirements for Bisexual set preffered gender - BOTH");
		modify($pr){setPrefferedGender(Gender.BOTH);};
end;

rule "F + Straight"
	agenda-group "partner-requirements"
	when
		$u: User(gender==Gender.FEMALE, sexualOrientation==SexualOrientation.HETEROSEXUAL );
		$pr: PartnerRequirements(userId==$u.id, prefferedGender == null);
	then
		System.out.println("Partner Requirements for F + Straight set preffered gender - MALE");
		modify($pr){setPrefferedGender(Gender.MALE);};
end;

rule "F + Homosexual"
	agenda-group "partner-requirements"
	when
		$u: User(gender==Gender.FEMALE, sexualOrientation==SexualOrientation.HOMOSEXUAL );
		$pr: PartnerRequirements(userId==$u.id, prefferedGender == null);
	then
		System.out.println("Partner Requirements for F + Homosexual set preffered gender - FEMALE");
		modify($pr){setPrefferedGender(Gender.FEMALE);};
end;