package rules;

import com.ftn.uns.ac.rs.love_and_food.model.RegisteredUser;
import com.ftn.uns.ac.rs.love_and_food.model.PartnerRequirements;

import com.ftn.uns.ac.rs.love_and_food.model.enums.Children;
import com.ftn.uns.ac.rs.love_and_food.model.enums.SexualOrientation;
import com.ftn.uns.ac.rs.love_and_food.model.enums.Gender;
import com.ftn.uns.ac.rs.love_and_food.model.enums.DesiredRelationship;
import com.ftn.uns.ac.rs.love_and_food.model.enums.Age;

import com.ftn.uns.ac.rs.love_and_food.util.DateUtil;

//Children
rule "Partner Requirements set children"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser($children: children);
		$pr: PartnerRequirements(userId==$ru.id, children == null);
	then
		System.out.println("Partner Requirements set children");
		modify($pr){setChildren($children);};
end;

//Relationship
rule "Partner Requirements set desired relationship status"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser( $desiredRelationship: desiredRelationship);
		$pr: PartnerRequirements(userId==$ru.id, desiredRelationship == null);
	then
		System.out.println("Partner Requirements set desired relationship status");
		modify($pr){setDesiredRelationship($desiredRelationship);};
end;

//Age
rule "Age_18_20"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(18 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth)<= 20);
		$pr: PartnerRequirements(userId==$ru.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Age_18_20");
		modify($pr){setIdealAge(Age.AGE_18_20),getSuitableAge().add(Age.AGE_20_25);};
end;

rule "Age_20_25"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(20 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 25);
		$pr: PartnerRequirements(userId==$ru.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Age_20_25");
		modify($pr){setIdealAge(Age.AGE_20_25),getSuitableAge().add(Age.AGE_18_20), getSuitableAge().add(Age.AGE_25_30);};
end;

rule "Age_25_30"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(25 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 30);
		$pr: PartnerRequirements(userId==$ru.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("AGE_25_30");
		modify($pr){setIdealAge(Age.AGE_25_30),getSuitableAge().add(Age.AGE_20_25), getSuitableAge().add(Age.AGE_30_40);};
end;

rule "Age_30_40"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(30 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 40);
		$pr: PartnerRequirements(userId==$ru.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Age_30_40");
		modify($pr){setIdealAge(Age.AGE_30_40),getSuitableAge().add(Age.AGE_25_30), getSuitableAge().add(Age.AGE_40_50);};
end;

rule "Age_40_50"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(40 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 50);
		$pr: PartnerRequirements(userId==$ru.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("AGE_40_50");
		modify($pr){setIdealAge(Age.AGE_40_50),getSuitableAge().add(Age.AGE_30_40), getSuitableAge().add(Age.AGE_50_65);};
end;
	
rule "Age_50_65"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(50 < DateUtil.getDiffYears(dateOfBirth),  DateUtil.getDiffYears(dateOfBirth) <= 65);
		$pr: PartnerRequirements(userId==$ru.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Age_50_65");
		modify($pr){setIdealAge(Age.AGE_50_65),getSuitableAge().add(Age.AGE_40_50), getSuitableAge().add(Age.AGE_65_PLUS);};
end;

rule "Age_65+"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(65 < DateUtil.getDiffYears(dateOfBirth));
		$pr: PartnerRequirements(userId==$ru.id, idealAge == null, suitableAge.isEmpty());
	then
		System.out.println("Age_65+");
		modify($pr){setIdealAge(Age.AGE_65_PLUS),getSuitableAge().add(Age.AGE_50_65);};
end;

//Preffered gender
rule "M + Straight"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(gender==Gender.MALE, sexualOrientation==SexualOrientation.HETEROSEXUAL );
		$pr: PartnerRequirements(userId==$ru.id, prefferedGender == null);
	then
		System.out.println("M + Straight");
		modify($pr){setPrefferedGender(Gender.FEMALE);};
end;

rule "M + Homosexual"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(gender==Gender.MALE, sexualOrientation==SexualOrientation.HOMOSEXUAL );
		$pr: PartnerRequirements(userId==$ru.id, prefferedGender == null);
	then
		System.out.println("M + Homosexual");
		modify($pr){setPrefferedGender(Gender.MALE);};
end;

rule "Bisexual"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(gender==Gender.MALE, sexualOrientation==SexualOrientation.BISEXUAL );
		$pr: PartnerRequirements(userId==$ru.id, prefferedGender == null);
	then
		System.out.println("Bisexual");
		modify($pr){setPrefferedGender(Gender.BOTH);};
end;

rule "F + Straight"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(gender==Gender.FEMALE, sexualOrientation==SexualOrientation.HETEROSEXUAL );
		$pr: PartnerRequirements(userId==$ru.id, prefferedGender == null);
	then
		System.out.println("F + Straight");
		modify($pr){setPrefferedGender(Gender.MALE);};
end;

rule "F + Homosexual"
	agenda-group "partner-requirements"
	when
		$ru: RegisteredUser(gender==Gender.FEMALE, sexualOrientation==SexualOrientation.HOMOSEXUAL );
		$pr: PartnerRequirements(userId==$ru.id, prefferedGender == null);
	then
		System.out.println("F + Homosexual");
		modify($pr){setPrefferedGender(Gender.FEMALE);};
end;