package rules;
import com.ftn.uns.ac.rs.love_and_food.model.Restaurant;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.time.LocalTime;
global ArrayList<Restaurant> resultHours;

rule "Get restaurants with working hours in range"
	agenda-group "working-hours"
	when
		$restaurant: Restaurant(startingHours.isBefore(LocalTime.parse("13:00")) && endingHours.isAfter(LocalTime.parse("15:00")));
	then
	    resultHours.add($restaurant);
end


