package rules;

import com.ftn.uns.ac.rs.love_and_food.event.MateRatingEvent;
import com.ftn.uns.ac.rs.love_and_food.model.User;
import com.ftn.uns.ac.rs.love_and_food.model.Match;

import java.util.Set;

rule "User rating is below 2.5 and a minimum of 3 users rated the user"
	agenda-group "user-rating-event"
	when
        $re: MateRatingEvent($user: match.soulmate);
        $average: Number( doubleValue < 2.5) from accumulate(
            Match(soulmate == $user, $initiator : initiator, $rating: rating),
            average($rating)
        );
        accumulate(
            Match(soulmate == $user, $initiator : initiator, $rating: rating),
            $initiators: collectSet( $initiator )
        );
        eval($initiators.size() >= 3)
    then
    	System.out.println("WARNING: The rating of the user: " + $user.getEmail()+  " fell bellow 2.5 ( the rating is: " + $average + " )");
end;