package rules;

import com.ftn.uns.ac.rs.love_and_food.event.FailedLoginEvent;
import com.ftn.uns.ac.rs.love_and_food.model.RegisteredUser;

declare SuspiciousUserEvent
    @role(event)
    @expires(24h)
    user: RegisteredUser
    reason: String
end;

rule "5 failed login attempts in 2 minutes from one user account"
	agenda-group "failed-login-attempt"
	when
		$fle1: FailedLoginEvent($id: user.getId(), $user: user)
		Number(intValue >= 5) from accumulate (
			$fle2: FailedLoginEvent(
				user.getId() == $id) over window:time(2m),
			count($fle2)
		)
		not (SuspiciousUserEvent(user.getId() == $id, 
        	reason == "More than 5 unsuccessful login attempts in 2 minute from one user account."))
	then
    	String reason = "More than 5 unsuccessful login attempts in 2 minute from one user account.";
        insert(new SuspiciousUserEvent($user, reason));
        System.out.println("More than 5 unsuccessful login attempts in 2 minute from " + $user.getEmail());
end;